# Generated by Django 3.0.10 on 2020-10-17 17:56

import apps.news.models_services
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('content', djangocms_text_ckeditor.fields.HTMLField(verbose_name='Содержание')),
                ('date_and_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата Создания')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(default=apps.news.models_services.get_default_news_image_path, upload_to=apps.news.models_services.get_upload_news_image_path, verbose_name='Изображение')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150, verbose_name='Имя автора')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email автора')),
                ('content', djangocms_text_ckeditor.fields.HTMLField(max_length=450, verbose_name='Содержание')),
                ('date_and_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Комментарий к новости',
                'verbose_name_plural': 'Комментарии к новостям',
            },
        ),
    ]
