# Generated by Django 3.0.10 on 2020-10-17 18:49

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=450, verbose_name='Содержание'),
        ),
    ]
