# Generated by Django 3.0.10 on 2021-02-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201017_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
    ]
