# Generated by Django 3.0.10 on 2020-10-20 20:54

from django.db import migrations, models
import django.db.models.deletion
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroLinkPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='base_introlinkpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('link_url', models.URLField(verbose_name='Куда введет кнопка')),
                ('title', models.CharField(max_length=250, verbose_name='Название кнопки')),
                ('icon', fontawesome_5.fields.IconField(blank=True, max_length=60, null=True, verbose_name='Своя иконка для кнопки')),
                ('target_modal_id', models.CharField(blank=True, help_text='Если ссылка должна его открывать, когда такое есть, то link_url не работает, а самой ссылке добавляется класс .modal__link', max_length=250, null=True, verbose_name='ID модально окна, без #')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
