# Generated by Django 3.0.10 on 2020-11-19 12:56

import apps.base.models_services
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('base', '0003_auto_20201021_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContentModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='base_pagecontentmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('date_and_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата Создания')),
            ],
            options={
                'verbose_name': 'Содержание страницы',
                'verbose_name_plural': 'Содержания страниц',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='PageImageModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='base_pageimagemodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('date_and_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата Создания')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(default=apps.base.models_services.get_default_page_image_path, upload_to=apps.base.models_services.get_upload_page_image_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение к странице',
                'verbose_name_plural': 'Изображения к страницам',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
