# Generated by Django 3.0.10 on 2021-02-15 18:38

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('base', '0004_pagecontentmodel_pageimagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseText',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='base_basetext', serialize=False, to='cms.CMSPlugin')),
                ('content', django_summernote.fields.SummernoteTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
