# Generated by Django 3.0.10 on 2020-10-17 17:56

import apps.vacancies.models_services
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Короткое название вакансии', max_length=250, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание вакансии', verbose_name='Описание')),
                ('payment', models.CharField(help_text='Например: 30т. рублей/мес или 100р за каждый час', max_length=250, verbose_name='Оплата')),
                ('date_and_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и Время создания')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=apps.vacancies.models_services.get_upload_vacancy_image_path, verbose_name='Изображение')),
                ('form_page', models.ForeignKey(blank=True, help_text='Страница с формой, чтобы оставить заявку, если она есть', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='Форма для заявки')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='VacancyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=250, verbose_name='Имя заказчика')),
                ('customer_last_name', models.CharField(max_length=250, verbose_name='Фамилия заказчика')),
                ('customer_phone', models.CharField(help_text='Номер телефона в формате +7 (9**) (***)...', max_length=250, verbose_name='Номер телефона заказчика')),
                ('customer_email', models.EmailField(help_text='Например: my@email.ru', max_length=250, verbose_name='Email заказчика')),
                ('date_and_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('status', models.CharField(choices=[('UNREAD', 'Не прочитанно'), ('READ', 'Прочитанно')], default='UNREAD', max_length=10, verbose_name='Статус заявки')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.Vacancy', verbose_name='Выбранная вакансия')),
            ],
            options={
                'verbose_name': 'Заявка на вакансию',
                'verbose_name_plural': 'Заявки на вакансии',
            },
        ),
    ]
