# Generated by Django 3.0.10 on 2020-10-17 17:56

import apps.gallery.models_services
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Короткое описание фото', max_length=250, verbose_name='Название к фото')),
                ('date_and_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=apps.gallery.models_services.get_upload_gallery_image_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение в галерее',
                'verbose_name_plural': 'Изображения в галерее',
            },
        ),
    ]
