# Generated by Django 3.0.10 on 2020-10-17 17:56

import apps.info.info_services
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoImage',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='info_infoimage', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(help_text='Краткое описание', max_length=250, verbose_name='Название для изображения')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=apps.info.info_services.get_upload_info_image_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение к инфо секции',
                'verbose_name_plural': 'Изображения к инфо секции',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='InfoItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='info_infoitem', serialize=False, to='cms.CMSPlugin')),
                ('content', djangocms_text_ckeditor.fields.HTMLField(max_length=250, verbose_name='Текст')),
                ('font_awesome_class', models.CharField(help_text='Font-Awesome класс, например: "fas fa-eye" или "fab fa-vk". Определяет иконку объекта, можно подобрать на https://fontawesome.com/icons', max_length=250, verbose_name='Класс Font-Awesome')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='InfoText',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='info_infotext', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(help_text='Например: Гала ТВ', max_length=250, verbose_name='Название')),
                ('text', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Информационный текст',
                'verbose_name_plural': 'Информационные текста',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
