# Generated by Django 3.1.2 on 2020-10-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestsMailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_request', models.CharField(choices=[('ConnectRequest', 'Заявки на подключение интернета'), ('ServiceRequest', 'Заявки на оказание услуг'), ('VacancyRequest', 'Заявки на вакансии')], help_text='Выберите тип зявок, при создании которых будет происходить рассылка', max_length=250, verbose_name='Тип заявок')),
            ],
            options={
                'verbose_name': 'Рассылка на какие-либо заявки',
                'verbose_name_plural': 'Рассылки на какие-либо заявки',
            },
        ),
        migrations.CreateModel(
            name='MailingEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='E-mail для которого можно установить рассылку, например: my@mail.com или info@galatv.ru', max_length=254, verbose_name='E-mail для рассылок')),
                ('mailings', models.ManyToManyField(help_text='Рассылки, которые будут приходить на этой E-mail.', to='mails.RequestsMailing', verbose_name='Расслыки')),
            ],
            options={
                'verbose_name': 'Почтовый адрес, для рассылок',
                'verbose_name_plural': 'Почтовые адреса, для рассылок',
            },
        ),
    ]
