# Generated by Django 3.0.10 on 2020-10-19 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_auto_20201005_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'E-mail Рассылка', 'verbose_name_plural': 'E-mail Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailingemail',
            options={'verbose_name': 'Почтовый адрес, для рассылки', 'verbose_name_plural': 'Почтовые адреса, для рассылки'},
        ),
        migrations.RemoveField(
            model_name='mailingemail',
            name='mailing',
        ),
        migrations.AddField(
            model_name='mailing',
            name='email_to_send',
            field=models.ForeignKey(help_text='E-mail, на который будет приходить рассылка', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mails.MailingEmail', verbose_name='E-mail, для рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='type_of_mailing',
            field=models.CharField(choices=[('ConnectRequest', 'При создании заявок на подключение интернета или ТВ'), ('ServiceRequest', 'При создании заявок на оказание услуг'), ('VacancyRequest', 'При создании заявок на вакансии')], help_text='Выберите, когда будет происходить рассылка', max_length=250, verbose_name='Тип рассылки'),
        ),
    ]
