# Generated by Django 3.0.10 on 2020-10-17 17:56

import apps.services.local_services
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='services_service', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Краткое описание', null=True, verbose_name='Описание')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=apps.services.local_services.get_service_image_upload_path, verbose_name='Изображение')),
                ('form_page', models.ForeignKey(blank=True, help_text='Страница с формой, для заказа услуги', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='Форма заказа')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=250, verbose_name='Имя заказчика')),
                ('customer_last_name', models.CharField(max_length=250, verbose_name='Фамилия заказчика')),
                ('customer_phone', models.CharField(help_text='Номер телефона в формате +7 (9**) (***)...', max_length=250, verbose_name='Номер телефона заказчика')),
                ('customer_email', models.EmailField(help_text='Например: my@email.ru', max_length=250, verbose_name='Email заказчика')),
                ('customer_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('date_and_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('status', models.CharField(choices=[('UNREAD', 'Не прочитанно'), ('READ', 'Прочитанно'), ('SUCCESS', 'Выполненно')], default='UNREAD', max_length=10, verbose_name='Статус заявки')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service', verbose_name='Выбранная услуга')),
            ],
            options={
                'verbose_name': 'Заявка на оказания услуги',
                'verbose_name_plural': 'Заявки на оказания услуги',
            },
        ),
    ]
