# Generated by Django 3.0.10 on 2020-10-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='customer_address',
            field=models.CharField(help_text='Физический адрес', max_length=250, null=True, verbose_name='Адрес заказчика'),
        ),
    ]
