# Generated by Django 3.0.10 on 2021-02-14 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('services', '0002_servicerequest_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detail_page',
            field=models.ForeignKey(blank=True, help_text='Страница с подробным описанием услуги, если она есть', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_page', to='cms.Page', verbose_name='Своя страница услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='form_page',
            field=models.ForeignKey(blank=True, help_text='Страница с формой, для заказа услуги', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_page', to='cms.Page', verbose_name='Форма заказа'),
        ),
    ]
