# Generated by Django 3.0.10 on 2021-02-14 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('services', '0003_auto_20210214_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestFormModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='services_servicerequestformmodel', serialize=False, to='cms.CMSPlugin')),
                ('service', models.ForeignKey(blank=True, default=None, help_text='Если нужна форма для конкретной услуги, для общей, оставьте поле пустым.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Service', verbose_name='Конкретная услуга, для этой формы')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
