# Generated by Django 3.0.10 on 2020-10-17 17:56

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMapModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='maps_googlemapmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', djangocms_text_ckeditor.fields.HTMLField(blank=True, max_length=250, null=True, verbose_name='Заголовок')),
                ('location_map', models.CharField(max_length=500, verbose_name='Iframe код из Google Maps')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
