# Generated by Django 3.0.10 on 2020-10-17 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='sections_section', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок')),
                ('sub_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Подзаголовок')),
                ('page_link_text', models.CharField(blank=True, help_text='Текст кнопки с ссылкой на отдельную страницу секции, если она есть', max_length=250, null=True, verbose_name='Текст ссылки на старинцу секции')),
                ('page', models.ForeignKey(blank=True, help_text='Отдельная страница, для этой секции, если она есть', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='Своя страница, для секции')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
