# Generated by Django 3.0.10 on 2020-10-17 17:56

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Киров или Мурыгино', max_length=250, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Например: Эта зона тарифов действует в Ленинском районе города Кирова', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Зона Охвата Тарифа (Город, Посёлок, и т.д)',
                'verbose_name_plural': 'Зоны Охвата Тарифов',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rates_rate', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(help_text='Например: Premium или Lite', max_length=250, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Например: Этот тариф идеально подходит, для домашнего использования, т.к. в нём есть кабельное ТВ', null=True, verbose_name='Описание')),
                ('internet_speed', models.PositiveIntegerField(help_text='(В МБТ/C)', verbose_name='Скорость интернета')),
                ('price', models.PositiveIntegerField(help_text='(В РУБ/МЕСЯЦ) Без учёта Телевидения', verbose_name='Цена тарифа')),
                ('color', colorfield.fields.ColorField(default='#54AC8A', help_text='Отличительный цвет тарифа', max_length=18, verbose_name='Свой цвет')),
                ('show_on_main_page', models.BooleanField(help_text='Тариф будет виден на главной в секции тарифы', verbose_name='Показывать на Главной странице')),
                ('have_tv', models.BooleanField(verbose_name='Имеется в тарифе ТВ')),
                ('price_tv', models.PositiveIntegerField(blank=True, help_text='В РУБ (Если оно имеется). Эта цена будет суммироваться с обычной', null=True, verbose_name='Цена ТВ')),
                ('form_page', models.ForeignKey(blank=True, help_text='Страница с формой, для заказа тарифа, если она есть', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='Форма для заказа')),
                ('place', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rates.Place', verbose_name='Место, зоны охвата тарифа')),
            ],
            options={
                'verbose_name': 'Интернет-Тариф',
                'verbose_name_plural': 'Интернет тарифы',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ConnectRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_tv', models.BooleanField(blank=True, null=True, verbose_name='Подключать ТВ')),
                ('customer_name', models.CharField(max_length=250, verbose_name='Имя заказчика')),
                ('customer_last_name', models.CharField(max_length=250, verbose_name='Фамилия заказчика')),
                ('customer_phone', models.CharField(help_text='Номер телефона в формате +7 (9**) (***)...', max_length=250, verbose_name='Номер телефона заказчика')),
                ('customer_email', models.EmailField(help_text='Например: my@email.ru', max_length=250, verbose_name='Email заказчика')),
                ('customer_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('date_and_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('status', models.CharField(choices=[('UNREAD', 'Не прочитанно'), ('READ', 'Прочитанно'), ('SUCCESS', 'Выполненно')], default='UNREAD', max_length=10, verbose_name='Статус заявки')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.Rate', verbose_name='Выбранный тариф')),
            ],
            options={
                'verbose_name': 'Заявка на подключение',
                'verbose_name_plural': 'Заявки на подключение',
            },
        ),
    ]
