# Generated by Django 3.0.10 on 2021-02-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_connectrequest_customer_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['view_position'], 'verbose_name': 'Интернет-Тариф', 'verbose_name_plural': 'Интернет тарифы'},
        ),
        migrations.AddField(
            model_name='rate',
            name='view_position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
